// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PersonalShow struct {
	// @gotags: gorm:"column:id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// @gotags: gorm:"column:person_id"
	PersonID int64 `protobuf:"varint,2,opt,name=personID,proto3" json:"personID,omitempty"`
	// @gotags: gorm:"column:person_name"
	Name            string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ShowDescription string `protobuf:"bytes,5,opt,name=showDescription,proto3" json:"showDescription,omitempty"`
	// @gotags: gorm:"column:by_time_weight"
	Weight float32 `protobuf:"fixed32,6,opt,name=weight,proto3" json:"weight,omitempty"`
	// @gotags: gorm:"column:by_time_tall"
	Tall float32 `protobuf:"fixed32,7,opt,name=tall,proto3" json:"tall,omitempty"`
	// @gotags: gorm:"column:by_time_age"
	Age int64 `protobuf:"varint,8,opt,name=age,proto3" json:"age,omitempty"`
	// @gotags: gorm:"column:visiable"
	Visiable             bool     `protobuf:"varint,9,opt,name=visiable,proto3" json:"visiable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonalShow) Reset()         { *m = PersonalShow{} }
func (m *PersonalShow) String() string { return proto.CompactTextString(m) }
func (*PersonalShow) ProtoMessage()    {}
func (*PersonalShow) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{0}
}

func (m *PersonalShow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonalShow.Unmarshal(m, b)
}
func (m *PersonalShow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonalShow.Marshal(b, m, deterministic)
}
func (m *PersonalShow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonalShow.Merge(m, src)
}
func (m *PersonalShow) XXX_Size() int {
	return xxx_messageInfo_PersonalShow.Size(m)
}
func (m *PersonalShow) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonalShow.DiscardUnknown(m)
}

var xxx_messageInfo_PersonalShow proto.InternalMessageInfo

func (m *PersonalShow) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PersonalShow) GetPersonID() int64 {
	if m != nil {
		return m.PersonID
	}
	return 0
}

func (m *PersonalShow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersonalShow) GetShowDescription() string {
	if m != nil {
		return m.ShowDescription
	}
	return ""
}

func (m *PersonalShow) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *PersonalShow) GetTall() float32 {
	if m != nil {
		return m.Tall
	}
	return 0
}

func (m *PersonalShow) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *PersonalShow) GetVisiable() bool {
	if m != nil {
		return m.Visiable
	}
	return false
}

func init() {
	proto.RegisterType((*PersonalShow)(nil), "api.PersonalShow")
}

func init() { proto.RegisterFile("type.proto", fileDescriptor_8eaed4801c3a9059) }

var fileDescriptor_8eaed4801c3a9059 = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xb1, 0x4a, 0x04, 0x31,
	0x10, 0x86, 0xc9, 0xae, 0xc6, 0xdc, 0x20, 0x2a, 0x53, 0xc8, 0x60, 0x15, 0xac, 0x52, 0xad, 0x85,
	0x6f, 0x20, 0xd7, 0xd8, 0x49, 0xec, 0xec, 0x72, 0x5e, 0xb8, 0x1d, 0x88, 0x9b, 0xb0, 0x09, 0x2e,
	0xbe, 0xa6, 0x4f, 0x24, 0x3b, 0xc8, 0x16, 0xd7, 0xfd, 0xdf, 0xf7, 0xc3, 0xf0, 0x0f, 0x40, 0xfb,
	0x29, 0x71, 0x28, 0x73, 0x6e, 0x19, 0xfb, 0x50, 0xf8, 0xf1, 0x57, 0xc1, 0xf5, 0x5b, 0x9c, 0x6b,
	0x9e, 0x42, 0x7a, 0x1f, 0xf3, 0x82, 0x37, 0xd0, 0xf1, 0x91, 0x94, 0x55, 0xae, 0xf7, 0x1d, 0x1f,
	0xf1, 0x01, 0x4c, 0x91, 0xfe, 0x75, 0x4f, 0x9d, 0xd8, 0x8d, 0x11, 0xe1, 0x62, 0x0a, 0x5f, 0x91,
	0x7a, 0xab, 0xdc, 0xce, 0x4b, 0x46, 0x07, 0xb7, 0x75, 0xcc, 0xcb, 0x3e, 0xd6, 0xcf, 0x99, 0x4b,
	0xe3, 0x3c, 0xd1, 0xa5, 0xd4, 0xe7, 0x1a, 0xef, 0x41, 0x2f, 0x91, 0x4f, 0x63, 0x23, 0x6d, 0x95,
	0xeb, 0xfc, 0x3f, 0xad, 0x57, 0x5b, 0x48, 0x89, 0xae, 0xc4, 0x4a, 0xc6, 0x3b, 0xe8, 0xc3, 0x29,
	0x92, 0x91, 0x01, 0x6b, 0x5c, 0x77, 0x7d, 0x73, 0xe5, 0x70, 0x48, 0x91, 0x76, 0x56, 0x39, 0xe3,
	0x37, 0x7e, 0x31, 0x1f, 0x7a, 0x18, 0x9e, 0x42, 0xe1, 0x83, 0x96, 0x57, 0x9f, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x91, 0x9f, 0x9c, 0xe4, 0xf8, 0x00, 0x00, 0x00,
}
